### ISSUE TITLE
Not working with docpad 6.80.3

### ISSUE THREAD

**Issue by johnwu** [markgrovs/docpad-plugin-dateurls#13]
Was working with docpad 6.79.4, but after updating to 6.80.3 seeing the following error:

TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new DateUrls (/Volumes/Data/Users/user/Documents/projects/sparkbooth.com/node_modules/docpad-plugin-dateurls/out/dateurls.plugin.js:17:45)
    at PluginLoader.create (/Volumes/Data/Users/user/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:260:26)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3600:29
    at PluginLoader.load (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:240:7)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3595:27
    at PluginLoader.unsupported (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:146:7)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/docpad.js:3573:25
    at success (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:71:16)
    at safefs.readFile (/Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/esnext/lib/plugin-loader.js:110:18)
    at /Volumes/Data/Users/username/.nvm/versions/node/v8.11.3/lib/node_modules/docpad/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by markgrovs** [comment]
hi @johnwu sorry, I no longer use DocPad, feel free to fork and update.

**Comment by johnwu** [comment]
How about transferring it Docpad to maintain?
https://docpad.org/docs/plugin-write#maintenance

**Comment by markgrovs** [comment]
@bevryme would you like me to transfer this plugin?

**Comment by balupton** [comment]
The aforementioned issue with that plugin is still not resolved as it still needs https://github.com/bevry/boundation run on it to upgrade it to the latest conventions. 

Which is small effort on my part, however many of the community plugins still need this done. Is this dateurls plugin the only issue you are having?

That said, DocPad is officially marked as deprecated as there were months-year of unpaid full time put into it. As per the notice on https://docpad.bevry.me and unless someone wishes to pay for its maintenance then it just bleeds me dry, for the benefit of others only, a slavery of servitude, and from satiating work. That said, there is about a hundred hours of work left to sort out all the remaining issues with DocPad.

For Semantic UI, I'd suggest just going all in on React, with Gatsby or Next as the generator. Or if you care about generic use, then Stencil by Ionic is precisely for design systems like Stencil.

**Comment by balupton** [comment]
I've done the prep work for compat. Someone just needs to fix the error it is encountering in the tests:

```
dateurls plugin ➞ init ➞ create
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:980:7)
    at resolvePath (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:1998:23)
    at DocPad.getPath (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2092:58)
    at /Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2052:27
    at Array.map (<anonymous>)
    at DocPad.<anonymous> (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2051:39)
    at DocPad.getPath (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2091:10)
    at DocPad.<anonymous> (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2055:25)
    at DocPad.getPath (/Users/balupton/Projects/docpad/docpad-plugin-dateurls/node_modules/docpad/edition-esnext/lib/docpad.js:2091:10)

```
